import { useState } from 'react'
import { authService } from '../services/auth'

export default function AuthForm({ onLogin, notify, toast, Brand, Field }) {
  const [register, setRegister] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmation, setShowConfirmation] = useState(false)
  const [busy, setBusy] = useState(false)
  const [form, setForm] = useState({ firstName: '', lastName: '', email: '', password: '', confirmPassword: '', businessName: '', businessType: 'Tienda de barrio' })
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event) => { event.preventDefault(); if (register && form.password !== form.confirmPassword) { notify('Las contraseñas no coinciden'); return } setBusy(true); try { const result = register ? await authService.register(form) : await authService.login(form.email, form.password); onLogin(result) } catch (error) { notify(error.message) } finally { setBusy(false) } }
  return <main className="auth-shell"><section className="auth-story"><Brand /><div className="story-copy"><span className="eyebrow">GESTIÓN INTELIGENTE</span><h1>Más control.<br /><em>Menos vueltas.</em></h1><p>Ventas, inventario y decisiones claras para el día a día de tu negocio.</p></div><div className="story-note">NEXA COMMERCE <span>2026</span></div></section><section className="auth-panel"><div className="auth-form"><span className="step">{register ? '01 / REGISTRO' : '01 / ACCESO'}</span><h2>{register ? 'Crea tu negocio' : 'Hola, de nuevo.'}</h2><p className="muted">{register ? 'Empieza a trabajar con información real.' : 'Entra a tu operación en un solo paso.'}</p><form onSubmit={submit}>{register && <div className="form-row"><Field label="Nombre" value={form.firstName} onChange={(v) => update('firstName', v)} required /><Field label="Apellido" value={form.lastName} onChange={(v) => update('lastName', v)} required /></div>}<Field label="Correo electrónico" type="email" value={form.email} onChange={(v) => update('email', v)} required /><Field label="Contraseña" type={showPassword ? 'text' : 'password'} value={form.password} onChange={(v) => update('password', v)} required trailing={<button type="button" className="password-toggle" onClick={() => setShowPassword((value) => !value)}>{showPassword ? 'Ocultar' : 'Mostrar'}</button>} />{register && <><Field label="Repetir contraseña" type={showConfirmation ? 'text' : 'password'} value={form.confirmPassword} onChange={(v) => update('confirmPassword', v)} required trailing={<button type="button" className="password-toggle" onClick={() => setShowConfirmation((value) => !value)}>{showConfirmation ? 'Ocultar' : 'Mostrar'}</button>} /><Field label="Nombre del negocio" value={form.businessName} onChange={(v) => update('businessName', v)} required /><label className="select-label">Tipo de negocio<select value={form.businessType} onChange={(e) => update('businessType', e.target.value)}>{['Tienda de barrio', 'Droguería', 'Panadería', 'Ferretería', 'Papelería', 'Minimercado', 'Tienda de ropa', 'Otro'].map((type) => <option key={type}>{type}</option>)}</select></label></>}<button className="primary-button" disabled={busy}>{busy ? 'Procesando...' : register ? 'Crear cuenta →' : 'Entrar al sistema →'}</button></form><button className="switch-auth" onClick={() => setRegister((value) => !value)}>{register ? 'Ya tengo una cuenta' : 'Crear una cuenta nueva'}</button></div></section>{toast && <div className="toast">× {toast}</div>}</main>
}
