import { useEffect, useState } from 'react'
import { api } from '../services/auth'

const money = (value) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(Number(value || 0))
const empty = { name: '', document: '', phone: '', email: '', address: '' }

export function Directory({ type, notify }) {
  const config = { customers: { title: 'Clientes', endpoint: 'customers', fields: ['document', 'phone', 'email'] }, suppliers: { title: 'Proveedores', endpoint: 'suppliers', fields: ['document', 'phone', 'email', 'address'] }, categories: { title: 'Categorías', endpoint: 'categories', fields: ['description'] } }[type]
  const [items, setItems] = useState([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false)
  const load = () => api.request(`/${config.endpoint}`).then(setItems).catch((error) => notify(error.message))
  useEffect(() => { load() }, [])
  const save = async (event) => { event.preventDefault(); try { await api.request(editing ? `/${config.endpoint}/${editing}` : `/${config.endpoint}`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify(form) }); notify(`${config.title.slice(0, -1)} ${editing ? 'actualizado' : 'creado'} correctamente.`); setOpen(false); setEditing(null); setForm(empty); load() } catch (error) { notify(error.message) } }
  const remove = async (id) => { if (!window.confirm('¿Está seguro de que desea eliminar este registro?')) return; try { await api.request(`/${config.endpoint}/${id}`, { method: 'DELETE' }); notify('Registro eliminado.'); load() } catch (error) { notify(error.message) } }
  const startEdit = (item) => { setEditing(item.id); setForm({ name: item.name, document: item.document || '', phone: item.phone || '', email: item.email || '', address: item.address || '', description: item.description || '' }); setOpen(true) }
  return <><div className="toolbar"><span className="muted">Administra la información de tu negocio.</span><button className="primary-button" onClick={() => { setForm(empty); setEditing(null); setOpen(true) }}>+ Nuevo registro</button></div>{open && <form className="panel product-form" onSubmit={save}><h2>{editing ? 'Editar' : 'Nuevo'} {config.title.slice(0, -1)}</h2><div className="form-row"><label className="field">Nombre<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label>{config.fields.slice(0, 2).map((field) => <label className="field" key={field}>{field[0].toUpperCase() + field.slice(1)}<input value={form[field] || ''} onChange={(e) => setForm({ ...form, [field]: e.target.value })} /></label>)}</div><div className="form-row">{config.fields.slice(2).map((field) => <label className="field" key={field}>{field[0].toUpperCase() + field.slice(1)}<input value={form[field] || ''} onChange={(e) => setForm({ ...form, [field]: e.target.value })} /></label>)}</div><div className="form-actions"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancelar</button><button className="primary-button">Guardar</button></div></form>}<div className="panel table-wrap"><table><thead><tr><th>Nombre</th><th>Documento / descripción</th><th>Contacto</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.document || item.description || '—'}</td><td>{item.phone || item.email || '—'}</td><td><button className="small-button" onClick={() => startEdit(item)}>Editar</button><button className="delete-button" onClick={() => remove(item.id)}>Eliminar</button></td></tr>)}</tbody></table>{!items.length && <div className="table-empty">No hay registros todavía.</div>}</div></>
}

export function Reports({ notify }) { const [summary, setSummary] = useState(null); const [top, setTop] = useState([]); useEffect(() => { api.request('/reports/summary').then(setSummary).catch((e) => notify(e.message)); api.request('/dashboard/top-products').then(setTop).catch(() => {}) }, []); const values = [['Ventas de hoy', summary?.today], ['Ventas de la semana', summary?.week], ['Ventas del mes', summary?.month], ['Productos', summary?.products], ['Stock bajo', summary?.lowStock], ['Agotados', summary?.outOfStock]]; return <><section className="stats-grid">{values.map(([label, value]) => <article className="stat stat-lavender" key={label}><span>{label}</span><strong>{label.includes('Ventas') ? money(value) : value ?? '—'}</strong><small>Datos de MySQL</small></article>)}</section><section className="panel report-list"><h2>Productos más vendidos</h2>{top.map((item) => <div className="history-line" key={item.name}><span>{item.name}<small>{item.quantity} unidades</small></span><strong>{money(item.total)}</strong></div>)}{!top.length && <p className="muted">Aún no hay ventas para generar este reporte.</p>}</section></> }
