import { useEffect, useState } from 'react'
import { api } from '../services/auth'

const money = (value) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(Number(value || 0))
const initial = { name: '', sku: '', description: '', salePrice: '', purchasePrice: '', stock: 0, minimumStock: 0, categoryId: '', supplierId: '', status: 'ACTIVO' }

export default function ProductManager({ notify }) {
  const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('TODOS'); const [form, setForm] = useState(initial); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false)
  const load = () => api.request(`/products?search=${encodeURIComponent(search)}`).then(setProducts).catch((error) => notify(error.message))
  useEffect(() => { load(); api.request('/categories').then(setCategories).catch(() => {}) }, [search])
  const visible = products.filter((item) => filter === 'TODOS' || (filter === 'BAJO' && item.stock > 0 && item.stock <= item.minimum_stock) || (filter === 'AGOTADO' && item.stock === 0) || (filter === 'NORMAL' && item.stock > item.minimum_stock))
  const save = async (event) => { event.preventDefault(); try { await api.request(editing ? `/products/${editing}` : '/products', { method: editing ? 'PUT' : 'POST', body: JSON.stringify(form) }); notify(editing ? 'Producto actualizado correctamente.' : 'Producto creado correctamente.'); setOpen(false); setEditing(null); setForm(initial); load() } catch (error) { notify(error.message) } }
  const remove = async (id) => { if (!window.confirm('¿Está seguro de que desea eliminar este producto?')) return; try { await api.request(`/products/${id}`, { method: 'DELETE' }); notify('Producto eliminado.'); load() } catch (error) { notify(error.message) } }
  const edit = (item) => { setEditing(item.id); setForm({ name: item.name, sku: item.sku, description: item.description || '', salePrice: item.sale_price, purchasePrice: item.purchase_price, stock: item.stock, minimumStock: item.minimum_stock, categoryId: item.category_id || '', supplierId: item.supplier_id || '', status: item.status }); setOpen(true) }
  return <><div className="toolbar"><input className="search" placeholder="Buscar por nombre o SKU..." value={search} onChange={(e) => setSearch(e.target.value)} /><select className="filter-select" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="TODOS">Todos los estados</option><option value="NORMAL">Stock normal</option><option value="BAJO">Stock bajo</option><option value="AGOTADO">Agotados</option></select><button className="primary-button" onClick={() => { setEditing(null); setForm(initial); setOpen(true) }}>+ Nuevo producto</button></div>{open && <form className="panel product-form" onSubmit={save}><h2>{editing ? 'Editar producto' : 'Registrar producto'}</h2><div className="form-row"><Field label="Nombre" value={form.name} set={(value) => setForm({ ...form, name: value })} required /><Field label="SKU / código" value={form.sku} set={(value) => setForm({ ...form, sku: value })} required /></div><div className="form-row"><Field label="Precio venta" type="number" value={form.salePrice} set={(value) => setForm({ ...form, salePrice: value })} required /><Field label="Precio compra" type="number" value={form.purchasePrice} set={(value) => setForm({ ...form, purchasePrice: value })} /><Field label="Stock" type="number" value={form.stock} set={(value) => setForm({ ...form, stock: value })} /><Field label="Stock mínimo" type="number" value={form.minimumStock} set={(value) => setForm({ ...form, minimumStock: value })} /></div><label className="select-label">Categoría<select value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })}><option value="">Sin categoría</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="form-actions"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancelar</button><button className="primary-button">Guardar producto</button></div></form>}<div className="panel table-wrap"><table><thead><tr><th>Producto</th><th>SKU</th><th>Precio</th><th>Stock</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{visible.map((product) => <tr key={product.id}><td><strong>{product.name}</strong><small>{product.category_name || 'Sin categoría'}</small></td><td>{product.sku}</td><td>{money(product.sale_price)}</td><td>{product.stock}</td><td><span className={`badge ${product.stock === 0 ? 'danger' : product.stock <= product.minimum_stock ? 'warning' : 'success'}`}>{product.stock === 0 ? 'Agotado' : product.stock <= product.minimum_stock ? 'Stock bajo' : 'Normal'}</span></td><td><button className="small-button" onClick={() => edit(product)}>Editar</button><button className="delete-button" onClick={() => remove(product.id)}>Eliminar</button></td></tr>)}</tbody></table>{!visible.length && <div className="table-empty">No hay productos que coincidan con los filtros.</div>}</div></>
}
function Field({ label, value, set, type = 'text', required }) { return <label className="field">{label}<input type={type} value={value} onChange={(e) => set(e.target.value)} required={required} min={type === 'number' ? 0 : undefined} /></label> }
