import { useEffect, useState } from 'react'
import { api } from '../services/auth'

const money = (value) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(Number(value || 0))

export default function SalesManager({ notify }) {
  const [products, setProducts] = useState([]); const [cart, setCart] = useState([]); const [sales, setSales] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { let mounted = true; Promise.all([api.request('/products'), api.request('/sales')]).then(([nextProducts, nextSales]) => { if (!mounted) return; setProducts(Array.isArray(nextProducts) ? nextProducts : []); setSales(Array.isArray(nextSales) ? nextSales : []) }).catch((requestError) => { if (!mounted) return; setError(requestError.message); notify(requestError.message) }).finally(() => { if (mounted) setLoading(false) }); return () => { mounted = false } }, [])
  const add = (product) => setCart((current) => { const existing = current.find((item) => item.id === product.id); if (existing && existing.quantity >= product.stock) return current; return existing ? current.map((item) => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...product, quantity: 1 }] })
  const changeQuantity = (id, quantity) => setCart((current) => current.map((item) => item.id === id ? { ...item, quantity: Math.max(1, Math.min(Number(quantity) || 1, item.stock)) } : item))
  const remove = (id) => setCart((current) => current.filter((item) => item.id !== id)); const total = cart.reduce((sum, item) => sum + Number(item.sale_price) * item.quantity, 0)
  const checkout = async () => { try { await api.request('/sales', { method: 'POST', body: JSON.stringify({ items: cart.map((item) => ({ productId: item.id, quantity: item.quantity })) }) }); notify('Venta registrada correctamente.'); setCart([]); const [nextProducts, nextSales] = await Promise.all([api.request('/products'), api.request('/sales')]); setProducts(nextProducts); setSales(nextSales) } catch (requestError) { notify(requestError.message) } }
  if (loading) return <section className="panel state-panel"><h2>Cargando ventas...</h2><p className="muted">Estamos consultando productos y ventas.</p></section>
  if (error) return <section className="panel state-panel"><h2>No se pudo cargar ventas</h2><p className="muted">{error}</p><button className="primary-button" onClick={() => window.location.reload()}>Reintentar</button></section>
  return <div className="sales-layout"><section className="panel"><div className="panel-title"><h2>Productos disponibles</h2><span>{products.length} productos</span></div><div className="product-picks">{products.map((product) => <button key={product.id} disabled={!product.stock} onClick={() => add(product)}><strong>{product.name}</strong><span>{money(product.sale_price)} · {product.stock} disponibles</span></button>)}</div>{!products.length && <p className="muted">No hay productos disponibles para vender.</p>}</section><section className="panel cart"><h2>Venta actual</h2>{cart.map((item) => <div className="cart-line" key={item.id}><span>{item.name}<input className="quantity-input" type="number" min="1" max={item.stock} value={item.quantity} onChange={(event) => changeQuantity(item.id, event.target.value)} /><button className="delete-button" onClick={() => remove(item.id)}>Quitar</button></span><strong>{money(item.sale_price * item.quantity)}</strong></div>)}{!cart.length && <p className="muted">Selecciona productos para agregarlos al carrito.</p>}<div className="cart-total"><span>Total</span><strong>{money(total)}</strong></div><button className="primary-button" disabled={!cart.length} onClick={checkout}>Confirmar venta →</button></section><section className="panel sales-history"><h2>Últimas ventas</h2>{sales.map((sale) => <div className="history-line" key={sale.id}><span>Venta #{sale.id}<small>{new Date(sale.created_at).toLocaleString('es-CO')}</small></span><strong>{money(sale.total)}</strong></div>)}{!sales.length && <p className="muted">Aún no hay ventas registradas.</p>}</section></div>
}
