import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import mysql from 'mysql2/promise'

const app = express()
const port = Number(process.env.PORT || 4000)
const pool = mysql.createPool({ host: process.env.DB_HOST || 'localhost', port: Number(process.env.DB_PORT || 3306), user: process.env.DB_USER || 'root', password: process.env.DB_PASSWORD || '', database: process.env.DB_NAME || 'nexa_commerce', waitForConnections: true, connectionLimit: 10 })
app.use(cors({ origin: process.env.FRONTEND_URL || 'http://localhost:5173' }))
app.use(express.json())
const ok = (res, data, message = 'Operación correcta', status = 200) => res.status(status).json({ success: true, message, data })
const fail = (res, message, status = 400) => res.status(status).json({ success: false, message })
const tokenFor = (user) => jwt.sign({ id: user.id, businessId: user.business_id, role: user.role }, process.env.JWT_SECRET || 'change-this-secret', { expiresIn: '8h' })
const publicUser = (user) => ({ id: user.id, firstName: user.first_name, lastName: user.last_name, name: `${user.first_name} ${user.last_name}`, email: user.email, role: user.role, businessName: user.business_name, businessType: user.business_type })
const auth = (req, res, next) => { try { req.user = jwt.verify((req.headers.authorization || '').replace('Bearer ', ''), process.env.JWT_SECRET || 'change-this-secret'); next() } catch { fail(res, 'Sesión no válida o expirada', 401) } }
const asyncRoute = (handler) => (req, res) => Promise.resolve(handler(req, res)).catch((error) => { console.error(error); fail(res, 'Error interno del servidor', 500) })

app.get('/api/health', (req, res) => ok(res, { service: 'nexa-api', status: 'online' }))
app.post('/api/auth/register', asyncRoute(async (req, res) => { const { firstName, lastName, email, password, businessName, businessType } = req.body; if (!firstName || !lastName || !email || !password || !businessName || !businessType) return fail(res, 'Todos los campos son obligatorios'); if (password.length < 8) return fail(res, 'La contraseña debe tener al menos 8 caracteres'); const connection = await pool.getConnection(); try { await connection.beginTransaction(); const [exists] = await connection.query('SELECT id FROM users WHERE email = ?', [email.toLowerCase()]); if (exists.length) { await connection.rollback(); return fail(res, 'El correo ya está registrado', 409) } const [business] = await connection.query('INSERT INTO businesses (name, business_type) VALUES (?, ?)', [businessName, businessType]); const hash = await bcrypt.hash(password, 12); const [created] = await connection.query('INSERT INTO users (business_id, first_name, last_name, email, password, role) VALUES (?, ?, ?, ?, ?, ?)', [business.insertId, firstName, lastName, email.toLowerCase(), hash, 'ADMIN']); await connection.commit(); const user = { id: created.insertId, first_name: firstName, last_name: lastName, email: email.toLowerCase(), role: 'ADMIN', business_name: businessName, business_type: businessType }; return ok(res, { token: tokenFor({ ...user, business_id: business.insertId }), user: publicUser({ ...user }) }, 'Cuenta creada correctamente', 201) } finally { connection.release() } }))
app.post('/api/auth/login', asyncRoute(async (req, res) => { const { email, password } = req.body; const [rows] = await pool.query('SELECT u.*, b.name business_name, b.business_type FROM users u JOIN businesses b ON b.id = u.business_id WHERE u.email = ?', [(email || '').toLowerCase()]); if (!rows.length || !(await bcrypt.compare(password || '', rows[0].password))) return fail(res, 'Las credenciales no son correctas', 401); return ok(res, { token: tokenFor(rows[0]), user: publicUser(rows[0]) }, 'Acceso concedido') }))
app.get('/api/auth/me', auth, asyncRoute(async (req, res) => { const [rows] = await pool.query('SELECT u.*, b.name business_name, b.business_type FROM users u JOIN businesses b ON b.id = u.business_id WHERE u.id = ?', [req.user.id]); return rows.length ? ok(res, publicUser(rows[0])) : fail(res, 'Usuario no encontrado', 404) }))

app.get('/api/categories', auth, asyncRoute(async (req, res) => { const [rows] = await pool.query('SELECT * FROM categories WHERE business_id = ? ORDER BY name', [req.user.businessId]); ok(res, rows) }))
app.post('/api/categories', auth, asyncRoute(async (req, res) => { const { name, description = '' } = req.body; if (!name) return fail(res, 'El nombre es obligatorio'); const [result] = await pool.query('INSERT INTO categories (business_id, name, description) VALUES (?, ?, ?)', [req.user.businessId, name, description]); ok(res, { id: result.insertId, name, description }, 'Categoría creada', 201) }))
app.put('/api/categories/:id', auth, asyncRoute(async (req, res) => { const { name, description = '', status = 'ACTIVA' } = req.body; const [result] = await pool.query('UPDATE categories SET name=?, description=?, status=? WHERE id=? AND business_id=?', [name, description, status, req.params.id, req.user.businessId]); result.affectedRows ? ok(res, null, 'Categoría actualizada') : fail(res, 'Categoría no encontrada', 404) }))
app.delete('/api/categories/:id', auth, asyncRoute(async (req, res) => { const [result] = await pool.query('DELETE FROM categories WHERE id=? AND business_id=?', [req.params.id, req.user.businessId]); result.affectedRows ? ok(res, null, 'Categoría eliminada') : fail(res, 'Categoría no encontrada', 404) }))
app.get('/api/products', auth, asyncRoute(async (req, res) => { const search = `%${req.query.search || ''}%`; const [rows] = await pool.query('SELECT p.*, c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.business_id=? AND (p.name LIKE ? OR p.sku LIKE ?) ORDER BY p.name', [req.user.businessId, search, search]); ok(res, rows) }))
app.post('/api/products', auth, asyncRoute(async (req, res) => { const { name, sku, description = '', categoryId = null, purchasePrice = 0, salePrice, stock = 0, minimumStock = 0 } = req.body; if (!name || !sku || Number(salePrice) <= 0 || Number(stock) < 0) return fail(res, 'Nombre, SKU, precio y stock válido son obligatorios'); const [result] = await pool.query('INSERT INTO products (business_id, category_id, name, sku, description, purchase_price, sale_price, stock, minimum_stock) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)', [req.user.businessId, categoryId, name, sku, description, purchasePrice, salePrice, stock, minimumStock]); ok(res, { id: result.insertId }, 'Producto creado correctamente', 201) }))
app.put('/api/products/:id', auth, asyncRoute(async (req, res) => { const { name, sku, description = '', categoryId = null, supplierId = null, purchasePrice = 0, salePrice, stock = 0, minimumStock = 0, status = 'ACTIVO' } = req.body; if (!name || !sku || Number(salePrice) <= 0 || Number(stock) < 0) return fail(res, 'Datos de producto inválidos'); const [result] = await pool.query('UPDATE products SET name=?, sku=?, description=?, category_id=?, supplier_id=?, purchase_price=?, sale_price=?, stock=?, minimum_stock=?, status=? WHERE id=? AND business_id=?', [name, sku, description, categoryId || null, supplierId || null, purchasePrice, salePrice, stock, minimumStock, status, req.params.id, req.user.businessId]); result.affectedRows ? ok(res, null, 'Producto actualizado') : fail(res, 'Producto no encontrado', 404) }))
app.delete('/api/products/:id', auth, asyncRoute(async (req, res) => { const [result] = await pool.query('DELETE FROM products WHERE id=? AND business_id=?', [req.params.id, req.user.businessId]); if (result.affectedRows) return ok(res, null, 'Producto eliminado'); return fail(res, 'Producto no encontrado', 404) }))
app.get('/api/inventory', auth, asyncRoute(async (req, res) => { const [rows] = await pool.query("SELECT p.*, c.name category_name, CASE WHEN p.stock=0 THEN 'AGOTADO' WHEN p.stock<=p.minimum_stock THEN 'BAJO' ELSE 'NORMAL' END stock_status FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.business_id=? ORDER BY p.stock ASC", [req.user.businessId]); ok(res, rows) }))
app.post('/api/inventory/movement', auth, asyncRoute(async (req, res) => { const { productId, type, quantity } = req.body; const connection = await pool.getConnection(); try { await connection.beginTransaction(); const [products] = await connection.query('SELECT * FROM products WHERE id=? AND business_id=? FOR UPDATE', [productId, req.user.businessId]); if (!products.length) return fail(res, 'Producto no encontrado', 404); const product = products[0]; const change = type === 'ENTRADA' ? Number(quantity) : -Number(quantity); const next = product.stock + change; if (next < 0) return fail(res, 'No hay suficiente inventario'); await connection.query('UPDATE products SET stock=? WHERE id=?', [next, productId]); await connection.query('INSERT INTO inventory_movements (business_id, product_id, user_id, type, quantity, previous_stock, new_stock) VALUES (?, ?, ?, ?, ?, ?, ?)', [req.user.businessId, productId, req.user.id, type, quantity, product.stock, next]); await connection.commit(); ok(res, { stock: next }, 'Inventario actualizado correctamente') } finally { connection.release() } }))
app.post('/api/sales', auth, asyncRoute(async (req, res) => { const { items, paymentMethod = 'EFECTIVO' } = req.body; if (!Array.isArray(items) || !items.length) return fail(res, 'La venta debe tener productos'); const connection = await pool.getConnection(); try { await connection.beginTransaction(); let total = 0; const checked = []; for (const item of items) { const [rows] = await connection.query('SELECT * FROM products WHERE id=? AND business_id=? FOR UPDATE', [item.productId, req.user.businessId]); if (!rows.length || rows[0].stock < item.quantity) { await connection.rollback(); return fail(res, 'No hay suficiente inventario', 409) } const subtotal = rows[0].sale_price * item.quantity; total += subtotal; checked.push({ product: rows[0], quantity: item.quantity, subtotal }) } const [sale] = await connection.query('INSERT INTO sales (business_id, user_id, total, payment_method) VALUES (?, ?, ?, ?)', [req.user.businessId, req.user.id, total, paymentMethod]); for (const item of checked) { await connection.query('INSERT INTO sale_details (sale_id, product_id, quantity, unit_price, subtotal) VALUES (?, ?, ?, ?, ?)', [sale.insertId, item.product.id, item.quantity, item.product.sale_price, item.subtotal]); await connection.query('UPDATE products SET stock=stock-? WHERE id=?', [item.quantity, item.product.id]); await connection.query('INSERT INTO inventory_movements (business_id, product_id, user_id, type, quantity, previous_stock, new_stock) VALUES (?, ?, ?, ?, ?, ?, ?)', [req.user.businessId, item.product.id, req.user.id, 'VENTA', item.quantity, item.product.stock, item.product.stock - item.quantity]) } await connection.commit(); ok(res, { id: sale.insertId, total }, 'Venta registrada correctamente', 201) } finally { connection.release() } }))
app.get('/api/sales', auth, asyncRoute(async (req, res) => { const [rows] = await pool.query('SELECT s.*, CONCAT(u.first_name, " ", u.last_name) user_name FROM sales s JOIN users u ON u.id=s.user_id WHERE s.business_id=? ORDER BY s.created_at DESC LIMIT 50', [req.user.businessId]); ok(res, rows) }))
app.get('/api/customers', auth, asyncRoute(async (req, res) => { const [rows] = await pool.query('SELECT * FROM customers WHERE business_id=? ORDER BY name', [req.user.businessId]); ok(res, rows) }))
app.post('/api/customers', auth, asyncRoute(async (req, res) => { const { name, document = '', phone = '', email = '' } = req.body; if (!name) return fail(res, 'El nombre es obligatorio'); const [result] = await pool.query('INSERT INTO customers (business_id,name,document,phone,email) VALUES (?,?,?,?,?)', [req.user.businessId, name, document, phone, email]); ok(res, { id: result.insertId }, 'Cliente creado', 201) }))
app.put('/api/customers/:id', auth, asyncRoute(async (req, res) => { const { name, document = '', phone = '', email = '' } = req.body; const [result] = await pool.query('UPDATE customers SET name=?,document=?,phone=?,email=? WHERE id=? AND business_id=?', [name, document, phone, email, req.params.id, req.user.businessId]); result.affectedRows ? ok(res, null, 'Cliente actualizado') : fail(res, 'Cliente no encontrado', 404) }))
app.delete('/api/customers/:id', auth, asyncRoute(async (req, res) => { const [result] = await pool.query('DELETE FROM customers WHERE id=? AND business_id=?', [req.params.id, req.user.businessId]); result.affectedRows ? ok(res, null, 'Cliente eliminado') : fail(res, 'Cliente no encontrado', 404) }))
app.get('/api/suppliers', auth, asyncRoute(async (req, res) => { const [rows] = await pool.query('SELECT * FROM suppliers WHERE business_id=? ORDER BY name', [req.user.businessId]); ok(res, rows) }))
app.post('/api/suppliers', auth, asyncRoute(async (req, res) => { const { name, document = '', phone = '', email = '', address = '' } = req.body; if (!name) return fail(res, 'El nombre es obligatorio'); const [result] = await pool.query('INSERT INTO suppliers (business_id,name,document,phone,email,address) VALUES (?,?,?,?,?,?)', [req.user.businessId, name, document, phone, email, address]); ok(res, { id: result.insertId }, 'Proveedor creado', 201) }))
app.put('/api/suppliers/:id', auth, asyncRoute(async (req, res) => { const { name, document = '', phone = '', email = '', address = '' } = req.body; const [result] = await pool.query('UPDATE suppliers SET name=?,document=?,phone=?,email=?,address=? WHERE id=? AND business_id=?', [name, document, phone, email, address, req.params.id, req.user.businessId]); result.affectedRows ? ok(res, null, 'Proveedor actualizado') : fail(res, 'Proveedor no encontrado', 404) }))
app.delete('/api/suppliers/:id', auth, asyncRoute(async (req, res) => { const [result] = await pool.query('DELETE FROM suppliers WHERE id=? AND business_id=?', [req.params.id, req.user.businessId]); result.affectedRows ? ok(res, null, 'Proveedor eliminado') : fail(res, 'Proveedor no encontrado', 404) }))
app.get('/api/reports/summary', auth, asyncRoute(async (req, res) => { const [rows] = await pool.query("SELECT (SELECT COALESCE(SUM(total),0) FROM sales WHERE business_id=? AND DATE(created_at)=CURDATE()) today, (SELECT COALESCE(SUM(total),0) FROM sales WHERE business_id=? AND created_at>=DATE_SUB(CURDATE(), INTERVAL 7 DAY)) week, (SELECT COALESCE(SUM(total),0) FROM sales WHERE business_id=? AND MONTH(created_at)=MONTH(CURDATE()) AND YEAR(created_at)=YEAR(CURDATE())) month, (SELECT COUNT(*) FROM products WHERE business_id=?) products, (SELECT COUNT(*) FROM products WHERE business_id=? AND stock=0) outOfStock, (SELECT COUNT(*) FROM products WHERE business_id=? AND stock>0 AND stock<=minimum_stock) lowStock", [req.user.businessId, req.user.businessId, req.user.businessId, req.user.businessId, req.user.businessId, req.user.businessId]); ok(res, rows[0]) }))
app.get('/api/dashboard/top-products', auth, asyncRoute(async (req, res) => { const [rows] = await pool.query('SELECT p.name, SUM(sd.quantity) quantity, SUM(sd.subtotal) total FROM sale_details sd JOIN sales s ON s.id=sd.sale_id JOIN products p ON p.id=sd.product_id WHERE s.business_id=? GROUP BY p.id,p.name ORDER BY quantity DESC LIMIT 5', [req.user.businessId]); ok(res, rows) }))
app.get('/api/dashboard/stats', auth, asyncRoute(async (req, res) => { const [rows] = await pool.query("SELECT (SELECT COALESCE(SUM(total),0) FROM sales WHERE business_id=? AND DATE(created_at)=CURDATE()) todaySales, (SELECT COALESCE(SUM(total),0) FROM sales WHERE business_id=? AND MONTH(created_at)=MONTH(CURDATE()) AND YEAR(created_at)=YEAR(CURDATE())) monthSales, (SELECT COUNT(*) FROM products WHERE business_id=?) products, (SELECT COUNT(*) FROM products WHERE business_id=? AND stock>0 AND stock<=minimum_stock) lowStock, (SELECT COUNT(*) FROM products WHERE business_id=? AND stock=0) outOfStock, (SELECT COALESCE(SUM(stock*purchase_price),0) FROM products WHERE business_id=?) inventoryValue", [req.user.businessId, req.user.businessId, req.user.businessId, req.user.businessId, req.user.businessId, req.user.businessId]); ok(res, rows[0]) }))
app.use((req, res) => fail(res, 'Ruta no encontrada', 404))
app.listen(port, () => console.log(`Nexa API escuchando en http://localhost:${port}`))
